import assert from 'node:assert/strict';
import { createSimulation, advanceSimulation } from '../src/simulation.js';
const step=(s,inspection,reduced=false,count=240)=>{for(let i=0;i<count;i++)advanceSimulation(s,.05,{inspection,reduced,now:10000+i*50});};
const s=createSimulation();s.held=true;step(s,false);
assert(s.power>.99 && s.motorAngle>0 && s.crankAngle>0);
assert(s.effectPhase>0 && s.effectPhase<1);
const phase=s.effectPhase;step(s,true);assert.equal(s.effectPhase,phase);step(s,false);
s.held=false;step(s,false);assert.equal(s.power,0);assert.equal(s.speed,0);
const motor=s.motorAngle;step(s,true);assert.equal(s.explode,1);assert.equal(s.motorAngle,motor);
step(s,false);assert.equal(s.explode,0);
const reduced=createSimulation();reduced.held=true;step(reduced,false,true);
assert(reduced.power>.99);assert.equal(reduced.effectPhase,0);assert.equal(reduced.motorAngle,0);assert.equal(reduced.crankAngle,-.72);
step(reduced,true,true,1);assert.equal(reduced.explode,1);
step(reduced,false,true,1);assert.equal(reduced.explode,0);
const delayed=createSimulation(),regular=createSimulation();delayed.held=regular.held=true;
advanceSimulation(delayed,100,{inspection:false,reduced:false,now:10000});
advanceSimulation(regular,.05,{inspection:false,reduced:false,now:10000});
assert.deepEqual(delayed,regular);
const direct=createSimulation();direct.dragging=true;direct.lastDrag=10000;direct.dragImpulse=4;
advanceSimulation(direct,.05,{inspection:false,reduced:false,now:10001});assert(direct.power>0);assert.equal(direct.crankAngle,-.72);
assert.equal(createSimulation().effectPhase,0);
console.log('PASS: energy phase bounded, inspection/reduced-motion freeze, reset phase,  ramp, coast, inspection/reassembly, reduced-motion feedback without spin, delayed-frame clamp, direct drag input.');
